# Generated by scripts/homebrew-formula in remziduzagac/herdsman for each
# release; edits here are overwritten.
class Herdsman < Formula
  desc "Terminal workspace for running coding agents, with stacked panes"
  homepage "https://github.com/remziduzagac/herdsman"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/remziduzagac/herdsman/releases/download/v1.0.0/herdsman-macos-aarch64"
      sha256 "0a588e389acc9bf94717227e7782d8f9e017b031e1070e568fe361df327cc91a"
    end
    on_intel do
      url "https://github.com/remziduzagac/herdsman/releases/download/v1.0.0/herdsman-macos-x86_64"
      sha256 "0e4e5cb4eebc4130b453cf2319b4bee87630f148175267f59015af405d8193ff"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/remziduzagac/herdsman/releases/download/v1.0.0/herdsman-linux-aarch64"
      sha256 "62d70ddaf0e502f412284d4b7ea8a2303e94aed6eeee0fc2ecbe0f865a100123"
    end
    on_intel do
      url "https://github.com/remziduzagac/herdsman/releases/download/v1.0.0/herdsman-linux-x86_64"
      sha256 "0c9872d913b0bea84c0838c7045abbdd3b07998d1a76b01aa01fcb8d37828d3a"
    end
  end

  def install
    bin.install Dir["herdsman-*"].first => "herdsman"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/herdsman --version")
  end
end
