# Generated by scripts/homebrew-formula in remziduzagac/herdsman for each
# release; edits here are overwritten.
class Herdsman < Formula
  desc "Terminal workspace for running coding agents, with stacked panes"
  homepage "https://github.com/remziduzagac/herdsman"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/remziduzagac/herdsman/releases/download/v1.1.0/herdsman-macos-aarch64"
      sha256 "d78c106262bb73c477bceb22d894cb1beb730dbb8bff658ddaf5b9501e3edf36"
    end
    on_intel do
      url "https://github.com/remziduzagac/herdsman/releases/download/v1.1.0/herdsman-macos-x86_64"
      sha256 "019a886b4457065f05b48a9ab53c9d6e3b6d26fde6c54f2e23ed234c2129456f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/remziduzagac/herdsman/releases/download/v1.1.0/herdsman-linux-aarch64"
      sha256 "ce3b135387d975af4aa820133bb9746e1c54e705584b34bbcf56972cab838454"
    end
    on_intel do
      url "https://github.com/remziduzagac/herdsman/releases/download/v1.1.0/herdsman-linux-x86_64"
      sha256 "d443a42e43f0d078c7535fada7fe6bf8c6fa0acae45bf7e377cf7b2495865415"
    end
  end

  def install
    bin.install Dir["herdsman-*"].first => "herdsman"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/herdsman --version")
  end
end
